In [5]:
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

# 1. Load dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# 2. Normalize
x_train = x_train / 255.0
x_test = x_test / 255.0

# 3. Reshape for CNN
x_train = x_train.reshape(-1, 28, 28, 1)
x_test = x_test.reshape(-1, 28, 28, 1)

# 4. One-hot encoding
y_train_cat = to_categorical(y_train, 10)
y_test_cat = to_categorical(y_test, 10)

# 5. Build CNN + RNN Model
model = models.Sequential()

# CNN Layers
model.add(layers.Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)))
model.add(layers.MaxPooling2D((2,2)))
model.add(layers.Conv2D(64, (3,3), activation='relu'))
model.add(layers.MaxPooling2D((2,2)))

# Convert CNN output to sequence for LSTM
model.add(layers.Reshape((25, 64)))  # Adjust shape for LSTM: (timesteps, features)

# LSTM Layer
model.add(layers.LSTM(64))

# Dense Layers
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

# 6. Compile
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# 7. Train
model.fit(x_train, y_train_cat,
          epochs=5,
          batch_size=64,
          validation_split=0.2)

# 8. Evaluate
test_loss, test_acc = model.evaluate(x_test, y_test_cat)
print("Test Accuracy:", test_acc)

# 9. Confusion Matrix & Report
y_pred = model.predict(x_test)
y_pred_classes = np.argmax(y_pred, axis=1)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_classes))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_classes))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/5
750/750 ━━━━━━━━━━━━━━━━━━━━ 57s 73ms/step - accuracy: 0.6842 - loss: 0.9260 - val_accuracy: 0.9605 - val_loss: 0.1376
Epoch 2/5
750/750 ━━━━━━━━━━━━━━━━━━━━ 53s 71ms/step - accuracy: 0.9606 - loss: 0.1291 - val_accuracy: 0.9687 - val_loss: 0.1062
Epoch 3/5
750/750 ━━━━━━━━━━━━━━━━━━━━ 81s 70ms/step - accuracy: 0.9736 - loss: 0.0851 - val_accuracy: 0.9760 - val_loss: 0.0787
Epoch 4/5
750/750 ━━━━━━━━━━━━━━━━━━━━ 82s 70ms/step - accuracy: 0.9818 - loss: 0.0586 - val_accuracy: 0.9830 - val_loss: 0.0573
Epoch 5/5
750/750 ━━━━━━━━━━━━━━━━━━━━ 84s 72ms/step - accuracy: 0.9840 - loss: 0.0505 - val_accuracy: 0.9843 - val_loss: 0.0520
313/313 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.9851 - loss: 0.0505
Test Accuracy: 0.9871000051498413
313/313 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step
Confusion Matrix:
[[ 972    0    1    0    1    0    2    2    2    0]
 [   0 1123    2    0    1    0    3    5    1    0]
 [   1    3 1015    0    2    0    0    5    6    0]
 [   0    0    2  985    0